export default [
  { id: 1, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 2, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 3, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 4, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 5, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 6, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 7, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 8, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 9, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 10, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 11, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 12, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 13, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 14, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 15, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 16, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 17, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 18, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 19, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 20, nome: "Tiago Turibio", permissao: "Total", ativo: true },
  { id: 21, nome: "Tiago Turibio", permissao: "Total", ativo: true },
];
